### ISSUE TITLE
R, Python, Conda, Mamba versions?

### ISSUE THREAD

**Issue by mvanmoer** [bowers-illinois-edu/linux_work_environment#1]
Hi Jake, can you also add what versions of R, Python, Mamba, and Conda you're using? e.g. 
`$ R --version`

**Comment by jwbowers** [comment]
Hi Mark,

```
R --version
R version 4.3.3 (2024-02-29) -- "Angel Food Cake"
Copyright (C) 2024 The R Foundation for Statistical Computing
Platform: x86_64-conda-linux-gnu (64-bit)
```

For mamba/conda
```
(mambaR) ➜  ~ mamba --version
mamba 1.5.8
conda 24.3.0
```

Python:
```
(mambaR) ➜  ~ python --version
Python 3.12.2
```

**Comment by mvanmoer** [comment]
Is "mambaR" just the name of the environment you created?

**Comment by jwbowers** [comment]
Yes


Jake Bowers
http://jakebowers.org

**Comment by mvanmoer** [comment]
Okay! I had been googling "mambaR" and that is apparently a common name.
