### ISSUE TITLE
add new conda list or change conda_packages.txt

### ISSUE THREAD

**Issue by mvanmoer** [bowers-illinois-edu/linux_work_environment#2]
Hi Jake,
Can you change conda_packages.txt to be the output of 
`$ conda list -e > conda_packages.txt`
This puts it into a format that `mamba create` can ingest directly. It's less human-readable, so you might want both in the repo?
The idea is that as part of building the container, it will clone this repo and build the mamba env directly from that package list.

**Comment by jwbowers** [comment]
I think 0c6f4b2 does this.

i love the idea of using this repo for building the container. For sure I will be changing R packages and updating them as we go. So this will make things that much easier!

**Comment by mvanmoer** [comment]
Whaddya know, it works!

AFAICT, from the original lists, there were 2 packages in conda_packages.txt, but not in r_packages.csv:

- essentials
- recommended

And vice versa:

- biocmanager
- ckmeans.1d.dp
- datapreparation
- fabricatr
- manytestsr
- nvimcom
- onlinefdr
- rcppprogress

Any objections to having these other 8 to be installed by mamba?

**Comment by jwbowers** [comment]
I'd love them to be installed by mamba except for manytestsr (that is my package https://github.com/bowers-illinois-edu/manytestsr ). It is not on CRAN yet and I'm still making changes to it.
